--[[
    GRF Editor [Version - 1.8.0]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.0.3)

Navi_Scroll = {
	{ "NULL", 0, 0, "NULL", 0, 0 }
}
